### PR TITLE
Update rive-js with support for IK constraints

### PR DESCRIPTION
**Pull request by avivian**

### CODE REVIEW

**Review by luigi-rosso — APPROVED** [review]
LGTM!

**Comment by luigi-rosso** [comment]
Although it looks like some bounds test is failing... I don't think we changed anything there.

**Comment by avivian** [comment]
I'll have a look in the morning... Looks like it's looking for something from rive canvas, maybe that's moved somewhere

**Comment by luigi-rosso** [comment]
I think something might be messed up with rive-js build, I don't see rive_canvas.js in the package but I do see it in my local manual built version.

**Comment by luigi-rosso** [comment]
Wooo this looks good now @avivian.

**Comment by avivian** [comment]
Going to close this and reopen to keep commit history clean for change log!

**Pull request closed without merging**
